
# The location of the public and private key of the CA
# Passphrases are to be stored in 'config/settings.local.yml' as
# 'ca_passphrase'.
key_file: "<%= ENV['HOME'] %>/private/Fedict-IAM-INT-MobileAuthAppPOCCA.key.pem"
crt_file: "<%= ENV['HOME'] %>/public/Fedict-IAM-INT-MobileAuthAppPOCCA.crt.pem"

# Options for the intermediate certificate authority.
intermediate:
  country:      "BE"
  state:        "Vlaams-Brabant"
  city:         "Diegem"
  organization: "Deloitte"
  department:   "Audit & ERS"
  common_name:  "Mobile Authentication Server"
  email:        ""
  key_size:     4096
  valid_for:    600 # days

# Options for the client certificate.
client_crt:
  valid_for:    365 #days
